### ISSUE TITLE
Openinfo prevents Up Next from fully working

### ISSUE THREAD

**Issue by kbxy88** [a4k-openproject/script.extendedinfo#10]
I select an episode widget and the openinfo/show info screen appears and I hit play, select what addon I want to play from and episode plays. Then when the up next pop up to continue to next episode I select play. Instead of playing that next episode, it goes back to the first episodes ‘show info’ page. I have to back out of that info screen and THEN the next episode will automatically start to play. 

Normally you select next episode, it finds a source and plays. Any way around that?

Sorry if my title doesn’t sum the issue properly. 

I’m running 18.1 - Auramod - Seren / premiumizer / realizer /

**Comment by SerpentDrago** [comment]
I just tried to replicate this and could not . 


18.2 > aura mod > seren 

I clicked a episode on seren next up widget >> information > > more info (openinfo ) >> play .. >>> seren ... forwarded to end of episode waited for up next popup . clicked it , it then played the next episode fine

**Comment by SerpentDrago** [comment]
Noticed another bug though .. can you from seren next up widget > context menu > open info > play .. my play button doesn't work if i directly try to open   openinfo from the widget .. only if i go information > more info

**Comment by kbxy88** [comment]
Tested the bug you discovered and I too can’t get it to play when we go through the context menu. 

 Seren widget>Openinfo> play>premiumizer
https://streamable.com/mwd0c
I select yes to play next episode it goes back to Openinfo, it’s not till I hit back button does the delete in PM pop up appear. Then after I answer that it preps the next episode. 

If I just wait when it goes back to Openinfo and not press anything, it just sits there.

In another test I answered the PM popup before it went back to Openinfo and I realized next episode started without touching anything. I turned that popup off inside of pmzr and everything went as planned. So I guess the process was being held up by the PMZR popup and nothing to do with Openinfo. 

Sorry about that! But a chance to thank you for everything you do and the time you take to make it all possible!

**Comment by drinfernoo** [comment]
The "Up Next" add-on, as well as other similar implementations, like Premiumizer or Gaia have, shouldn't be affected by OpenInfo, as it simply calls the URI used by the add-on in question. If that add-on can't handle its own URI correctly, that's not really an issue here.
