### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kinetika1** [a4k-openproject/script.extendedinfo#11]
I ran into a Openinfo bug on Kodi 18.2 Android 9, Tannix TX6 Pro TV Box, not sure if there is a fix for this. In extendedinfo mod and then Wraith in Kodi 17.6 it is possible to set the action for a menu or submenu item, in skins like Aeon Nox, to open the categories "All Movies" & "All TV Shows" by assigning the action with the following line: ActivateWindows(Videos,"plugin://script.extendedinfo?info=allmovies", return) and ActivateWindows(Videos,"plugin://script.extendedinfo?info=alltvshows", return). In Openinfo it is not possible to choose "All Movies" & "All TV Shows"when trying to assign an action to menu item. Assigning "All Movies" & "All TV Shows" to favorites and then changing action to "All Movies" & "All TV Shows" from the Favorites category is a work around to have a menu or submenu item open them. However doing it this way or assigning a custom item with lines ActivateWindows(Videos,"plugin://script.extendedinfo?info=alltvshows", return) and/or ActivateWindows(Videos,"plugin://script.extendedinfo?info=alltvshows", return) both leads to the same bug in Openinfo in Kodi 18.2. When trying to play anything when these portals open like this instantly crashed Kodi. Anyone knows of a workaround, new command line or fix? Cheers

**Comment by drinfernoo** [comment]
Can you attach a copy of your debug/crash log from when Kodi crashes?

**Comment by Kinetika1** [comment]
I will try provide this a bit later

**Comment by Kinetika1** [comment]
Hi there, ok here is the crash log files as well as screenshots of the command actions assigned in Aeon Nox Silvo skin homescreen manager section. Also tested other skins and its all the same crash behavior as mentioned in the OP. Would be amazing if you guys can fix this. Many Thx
[kodi_playmedia cmd crash.log](https://github.com/a4k-openproject/script.extendedinfo/files/3317921/kodi_playmedia.cmd.crash.log)
![PlayMedia cmd play crash](https://user-images.githubusercontent.com/33095136/59977236-226f5000-95cf-11e9-8155-9b1eb3b180c9.png)
[kodi_activatewindow cmd crash.log](https://github.com/a4k-openproject/script.extendedinfo/files/3317924/kodi_activatewindow.cmd.crash.log)
![ActivateWindow cmd play crash](https://user-images.githubusercontent.com/33095136/59977243-32872f80-95cf-11e9-805e-0e39ef4730fa.png)
![Openinfo assign all movies or all tv shows not available](https://user-images.githubusercontent.com/33095136/59977250-416de200-95cf-11e9-9e7e-4a2ff42aeb2c.png)

**Comment by Kinetika1** [comment]
Hi there, was the info sufficient? Did it help?

**Comment by JayDee696969** [comment]
Same issue here with any skin ive tried on Leia. You cannot create a shortcut to anything in Openinfo. I usually like to have direct shortcuts that open "All Movies" or "All shows" and of course the Search option. Anything within openinfo you create a shortcut to makes Kodi crash after clicking Play.

**Comment by drinfernoo** [comment]
You can't use `ActivateWindow(...)` for these to work, but rather must use `RunScript(...)`.

For reference, the commands are as follows:

* "All Movies": `RunScript(script.extendedinfo, info=allmovies)`

* "All TV Shows": `RunScript(script.extendedinfo, info=alltvshows)`

* "Search": * "All Movies": `RunScript(script.extendedinfo, info=search_menu)`
