### ISSUE TITLE
[Bug] Kodi Force close if creating shortcuts to OpenInfo

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/script.extendedinfo#13]
**Describe the bug**
Its an issue that only affects kodi Leia. No problem in Krypton.  

**To Reproduce**
1. Open OpenInfo
2. Add All Movies, all tv shows, or Search to kodi favorites.
3. Open Kodi favorites
4. Open any shortcut (Search, All Movies, or All TV Shows)
5. Hit the Play option and choose a player. Kodi Force closes.
-Happens with any skin.
-Goal is to create skin shortcuts to these Open Info sections, but havent been able to with Leia because of this bug.

**Expected behavior**
Use shortcuts to OpenInfo sections without Kodi force closing.

**Platform**
- Kodi version (18.0 Leia, 18.1 Leia, etc...)
- Device (PC, Nvidia Shield, Mibox, Raspberry Pi, etc...)
- Operating System (Android, WIndows, etc...)

**Log File**
`2019-07-16 17:32:14.723 T:11680   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Users\Jay\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\DialogBaseInfo.py", line 116, in get_youtube_vids
                                                result = YouTube.search_youtube(search_str, limit=10)
                                              File "C:\Users\Jay\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\YouTube.py", line 78, in search_youtube
                                                videos = handle_youtube_videos(results['items'], extended=extended)
                                            KeyError: 'items'`

**Comment by kodiultimate** [comment]
If I get you correctly you are looking to add some sections to the sub menu on main screen ? if so why not skip adding to favourites and just create shortcust through skin & skin.shortcuts ?

**Comment by SOOTTV** [comment]
You could use shortcuts to OpenMeta instead and see if that fixes your issue

**Comment by JayDee696969** [comment]
> If I get you correctly you are looking to add some sections to the sub menu on main screen ? if so why not skip adding to favourites and just create shortcust through skin & skin.shortcuts ?

I know, have you tried it? If you did you would see it force close after hitting play. The favorites was just an easy example.

**Comment by JayDee696969** [comment]
> You could use shortcuts to OpenMeta instead and see if that fixes your issue

Dont want OpenMeta. I prefer the GUI look of Openinfo "All TV Shows", and "all Movies" section.

**Comment by drinfernoo** [comment]
@JayDigg Can you confirm this bug is still present in OpenInfo 6.1.1?

**Comment by JayDee696969** [comment]
> @JayDigg Can you confirm this bug is still present in OpenInfo 6.1.1?

Yes, it is. It was the first thing i tried and hoped for, lol.

**Comment by JayDee696969** [comment]
> @JayDigg Can you confirm this bug is still present in OpenInfo 6.1.1?

You also cant navigate to these sections using skin shortcuts (All TV Shows, All Movies, or Search)

**Comment by drinfernoo** [comment]
Was testing this a bit, and I believe I've narrowed it down to something like:

If a Kodi favorite or Skin Shortcut is pointed at any OpenInfo menu that launches into the "script interface", such that it opens *without* browsing directly through the add-on, Kodi isn't able to pass the correct info to the add-on in order to properly pass to the player.

A possible workaround is to point shortcuts to those sections via:

`My Add-ons -> Program Add-ons -> OpenInfo`

That should bypass the "script interface", and load in a standard Kodi list view. Be aware, this **may not** be an ironclad solution, as the add-on seems to have unexpected behaviors across different skins and/or shortcut pathways, and **will not** display the "fancy" browsing interface. You should be able to set any viewtype available to your skin in the standard Kodi lait view, however.

It's unknown at this time what the actual solution will be to resolve this bug.

**Comment by SerpentDrago** [comment]
as a workaround you can point shortcuts or favorites to this custom action 

`RunScript(script.extendedinfo,info=allmovies)  `
for the "all movies" section

replace 
`info=allmovies
`
to change where you want it  allmovies/alltvshows/etc

kodi favorite would look like this 
`<favourite name="All Movies" thumb="special://home/addons/script.extendedinfo/resources/skins/Default/media/tmdb/thumb.png">RunScript(script.extendedinfo,info=allmovies)</favourite>`

**Comment by JayDee696969** [comment]
> Was testing this a bit, and I believe I've narrowed it down to something like:
> 
> If a Kodi favorite or Skin Shortcut is pointed at any OpenInfo menu that launches into the "script interface", such that it opens _without_ browsing directly through the add-on, Kodi isn't able to pass the correct info to the add-on in order to properly pass to the player.
> 
> A possible workaround is to point shortcuts to those sections via:
> 
> `My Add-ons -> Program Add-ons -> OpenInfo`
> 
> That should bypass the "script interface", and load in a standard Kodi list view. Be aware, this **may not** be an ironclad solution, as the add-on seems to have unexpected behaviors across different skins and/or shortcut pathways, and **will not** display the "fancy" browsing interface. You should be able to set any viewtype available to your skin in the standard Kodi lait view, however.
> 
> It's unknown at this time what the actual solution will be to resolve this bug.

Ok, so the issue with this idea is that you cant navigate inside the addon by using Skin Shortcuts if you try getting there via program addons. Also tried adding the sections in OpenInfo via the program addons to favorites and  causes the same Force close. Serpent Dragos suggestion does work however!

**Comment by JayDee696969** [comment]
> as a workaround you can point shortcuts or favorites to this custom action
> 
> `RunScript(script.extendedinfo,info=allmovies) `
> for the "all movies" section
> 
> replace
> `info=allmovies `
> to change where you want it allmovies/alltvshows/etc
> 
> kodi favorite would look like this
> `<favourite name="All Movies" thumb="special://home/addons/script.extendedinfo/resources/skins/Default/media/tmdb/thumb.png">RunScript(script.extendedinfo,info=allmovies)</favourite>`

Thank-You!! This method DOES work and doesnt force close. Win Win. So would you know the way to open the search box also?

**Comment by JayDee696969** [comment]
> Thank-You!! This method DOES work and doesnt force close. Win Win. So would you know the way to open the search box also?

Got it, RunScript(script.extendedinfo,info=search_menu)

**Comment by drinfernoo** [comment]
@JayDigg Those are the correct way to do it. Unfortunately, Kodi just creates the wrong pathways when making favorites.
