### ISSUE TITLE
open info plays videos in background [Bug]

### ISSUE THREAD

**Issue by daveftw84** [a4k-openproject/script.extendedinfo#14]
when clicking on a video and then selecting an addon, the addon is finding a working source but its playing the video in the back ground. i have to close  openinfo to see the video

**Comment by daveftw84** [comment]
im noticing its happening when using venom addon. no matter the source or video

**Comment by drinfernoo** [comment]
This likely depends on what skin you're using. It doesn't happen to me on Estuary.

**Comment by daveftw84** [comment]
When I select Exodus redux seren or Gaia. The videos play normally

**Comment by drinfernoo** [comment]
@daveftw84 Then it's an issue with Venom.
