### ISSUE TITLE
[Bug] Trailers don't work in v6.2.3

### ISSUE THREAD

**Issue by cg00001** [a4k-openproject/script.extendedinfo#16]
At first I thought it was the Youtube addon update and I had to open that first and play a video from there.

Still doesn't work for my linux laptop, and for a friend with Nvidia shield.

**Comment by drinfernoo** [comment]
Are you referring to starting a trailer from the "standard" extended info dialog, or from OpenInfo's "Netflix" view? Auto trailers in the "Netflix" view? Or from another section, maybe? In any case, everything's working just fine for me in both views on my Shield, with Kodi 18.3 and the latest Shield OS 8.0 update.

Can you try and get a log file?

**Comment by cg00001** [comment]
It works fine on Krypton. On Leia I tried right-clicking on the movie after opening OpenInfo - All Movies. I tried the alternative browser in settings, and Netflix view without success.
I rarely use OpenInfo, so I tried clicking on a movie to select trailer from the next screen on the bottom. My build freezes to  "waiting" for minutes... If I open OpenInfo - All Movies and right-click on a movie and select Play, the OpenMeta addon selector shows up and it crashes Kodi instantly. 

I enabled all debug options for this, hope it helps it's from my Debian Linux laptop, with Kodi v18.3:
https://paste.ubuntu.com/p/YMwsCB2xgv/

**Comment by drinfernoo** [comment]
I would guess that it has to do the fact you are clearly running a build... And don't actually have version 6.2.3.

`2019-08-07 15:27:58.585 T:139968939117184 NOTICE: ADDON: script.extendedinfo v99996.2.3 installed`

Means that whoever makes that build has modified OpenInfo in some way and changed the version number.

Please start with a fresh install, and get another log if you can. This is the first I've heard of this issue, and I am unable to replicate it, but I am very suspicious that your build has done something wrong.

**Comment by cg00001** [comment]
> I would guess that it has to do the fact you are clearly running a build... And don't actually have version 6.2.3.
> 
> `2019-08-07 15:27:58.585 T:139968939117184 NOTICE: ADDON: script.extendedinfo v99996.2.3 installed`
> 
> Means that whoever makes that build has modified OpenInfo in some way and changed the version number.
> 
> Please start with a fresh install, and get another log if you can. This is the first I've heard of this issue, and I am unable to replicate it, but I am very suspicious that your build has done something wrong.

I installed the proper 6.2.3 version from OpenMeta repo and the issue was repeated.
I will do a fresh install of Kodi and reply, thank you.

**Comment by cg00001** [comment]
I did a fresh install of Kodi Leia.
I'm using Debian Linux (testing) and since I'm using Kodi Krypton too, I use Flatpak Kodi v18.3 version. Previously OpenInfo and OpenMeta worked fine with Flatpak.
I use open Radeon drivers with few issues (in multi-part videos like in Comedy Central it crashes on change sometimes).

I installed Kodi, OpenInfo, OpenMeta, IT addon (to check if a movie plays), and Kodi's log uploader which I had to ditch because it didn't upload old logs that show what happens like the one below.
I installed just the aftermath wizard of the build I'm using to be able to upload the old.log and made sure that OpenInfo did not update to the build's version.

It still crashes my Kodi.
Thanks for trying to help.
https://paste.ubuntu.com/p/STMFCCT4Dr/

**Comment by drinfernoo** [comment]
Can you please try and reproduce in a clean, non-build install? There's simply too much going on in there to point at the bug.

**Comment by cg00001** [comment]
OK, in a clean Kodi v18.3 (using Flatpak), I installed Youtube, OpenInfo, and OpenMeta in that order:
https://paste.ubuntu.com/p/Dfy7VMhzhS/

**Comment by cg00001** [comment]
I tried OpenMeta on a build some days ago (after all that time) and it works just fine.
Thank you.
