### ISSUE TITLE
TVDB[Bug]

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/script.extendedinfo#19]
TV Shows throw error when hitting Play. I know TVDB is the issue, but wondering if API needs to be updated, or if this will sort itself out. Just wanted to put it out there. Heres the log: https://justpaste.it/68051

**Comment by sbernstecker** [comment]
I am having the same issues plus some additional problems,  anytime I either try to use openinfo or openmeta,  I get a error message that is being generated by openmeta that says it has encountered an error read Kodi error log, or something along those lines.  This has  started when TVDB started having the issues that the are working to fix. At this time, tvdb has stated the bug has been fixed.
