### ISSUE TITLE
[Feature Request] Swap OpenMeta for TMDBH

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/script.extendedinfo#24]
Just a thought, I really like TMDBH. Seems much more advanced with better features than OpenMeta. However I really like the GUI of Extended Info. Sooo, is it possible to get rid of OpenMeta, and integrate  Extended Info with TMDBH instead?? That would be perfect IMO. Thanks!

**Comment by drinfernoo** [comment]
TheMovieDb Helper already provides every last functionality of both OpenMeta *and* OpenInfo, put together... plus a lot more.

All that needs to be done is for a skinner to make skin support, but that's not an issue here.
