### ISSUE TITLE
[Bug] Hardware acceleration-MediCodec (Surface)

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/script.extendedinfo#7]
**Describe the bug**
Ok, so with Netflix view enabled, and on devices that use MediaCodec (Surface) acceleration. The trailer does not play in the upper right corner like intended. It plays behind the GUI of netflix view (which looks pretty bad)
Disabling Surface acceleration fixes the problem, but causes other problems with video playback.

Examples of devices that use Surface acceleration are Nvidia Shield, Amazon Fire devices.

**Comment by drinfernoo** [comment]
This works fine for myself and many other testers on a variety of different devices, including Fire and Shield devices. Could you provide a video maybe, for some more context?

**Comment by JayDee696969** [comment]
Hmm, tried again and its working if i open it directly from the addon. Looks like its only a problem if I add All movies or All TV shows as a shortcut to the home screen. Ill keep testing and let you know in more precise detail. Thanks!

**Comment by JayDee696969** [comment]
The issue stems from creating shortcuts to openinfo.
