### ISSUE TITLE
[Feature Request] Add filter : language, region & with_original_language

### ISSUE THREAD

**Issue by dilandyechiel** [a4k-openproject/script.extendedinfo#8]
**Is your feature request related to a problem? Please describe.**
Staying in a multi language spoken country INDIA, in which Openinfo doesn't show 

1. Movies made in India
2. India is having multiple languages movies

**Describe the solution you'd like**
Solution to 1. Is to add region as a filter (available in TMDB API)
Solution to 2. Is to add language (can show dubbed movies) and add with_original_language filter (can show non dubbed and original language movie)

**Describe alternatives you've considered**
No TMDB/IMDB list available for full Indian movies, Also Not worthy to make new list as TMDB already have functionality to do it easily.

**Additional context**
For Example:
`https://api.themoviedb.org/3/discover/movie?api_key=[YOUR_KEY_HERE]&language=hi&region=IN&sort_by=release_date.desc&include_adult=false&include_video=false&page=1&release_date.lte=2019-04-01&with_original_language=hi`

**Comment by drinfernoo** [comment]
This should be coming in a future update.

**Comment by drinfernoo** [comment]
With the `language=hi` parameter, you won't get any plot information, and likely much of the other metadata will be missing as well.

Try this URL, and see how it works for you: `https://api.themoviedb.org/3/discover/movie?language=en&region=IN&include_adult=false&sort_by=release_date.desc&api_key=**********&page=1`

**Comment by onlytanmoy** [comment]
> This should be coming in a future update.

cool...that would be nice...thanks doc.

**Comment by dilandyechiel** [comment]
Thank you very much, got a peek also. :D
